name: Example Runs

on: push

jobs:
  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        last:
          - null
          - v1000
          - v1000.0.4
          - v1000-pre.2
          - v1000.0.3-beta.5
        scheme:
          - continuous
          - semantic
        type:
          - null
          - major
          - minor
          - patch
          - prerelease
        branch:
          - null
          - sample-branch
    steps:
      - uses: actions/checkout@v2

      - id: compute_tag
        uses: ./
        with:
          github_token: ${{ github.token }}
          tag: ${{ matrix.last }}
          branch: ${{ matrix.branch }}
          tag_fetch_depth: 20
          version_scheme: ${{ matrix.scheme }}
          version_type: ${{ matrix.type }}

      - name: print out computed tag
        run: echo "The next computed tag is $TAG"
        env:
          TAG: ${{ steps.compute_tag.outputs.next_tag }}
